lab03-master/models/Country.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Country extends ActiveRecord
{

}

lab03-master/controllers/ContinentController.php
<?php

namespace app\controllers;

use app\models\Continent;
use app\models\Country;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class ContinentController extends Controller
{
    public function actionIndex()
    {
        $continents = Continent::find()->asArray()->all();
        return $this->render('index', ['continents' => $continents]);
    }

    public function actionView($code = 'AF')
    {
        $continent = Continent::findOne(['code' => $code]);

        $countriesDataProvider = new ActiveDataProvider([
           'query' => Country::find()->where(['continent_id' => $continent['continent_id']]),
           'pagination' => [
               'pageSize' => 20,
           ]
        ]);
        return $this->render('view', compact('continent', 'countriesDataProvider'));
    }



}

lab03-master/controllers/CountryController.php
<?php

namespace app\controllers;

use app\models\Continent;
use app\models\Country;
use app\models\UpdateCountry;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class CountryController extends Controller
{
    public function actionView($code = 'UA')
    {
        $country = Country::findOne(['code' => $code]);
        $continent = Continent::findOne(['continent_id' => $country['continent_id']]);

        $countryDataProvider = new ActiveDataProvider([
           'query' => Country::findOne(['code' => $code])
        ]);

        return $this->render('view', compact('country', 'continent', 'countryDataProvider'));
    }

    public function actionEdit($code = 'UA')
    {
        $country = Country::findOne(['code' => $code]);
        $continent = Continent::findOne(['continent_id' => $country['continent_id']]);

        $model = new UpdateCountry();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                Yii::$app->session->setFlash('success', 'Дані збережені');
                $country->continent_id = $model->continent_id;
                $country->name = $model->name;
                $country->official_name = $model->official_name;
                $country->code = $model->code;
                $country->area = $model->area;
                $country->currency = $model->currency;
                $country->capital = $model->capital;
                $country->save();
                return $this->refresh();
            }
            else {
                Yii::$app->session->setFlash('error', 'Помилка редагування');
            }
        }

        return $this->render('edit', compact('country', 'continent', 'model'));
    }
}

lab03-master/views/country/edit.php
<?php


use app\models\Continent;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Редагування ' . $country['name'];

$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['continent/index']];
$this->params['breadcrumbs'][] = ['label' => $continent['name'], 'url' => ['continent/view', 'code' => $continent['code']]];
$this->params['breadcrumbs'][] = ['label' => $country['name'], 'url' => ['country/view', 'code' => $country['code']]];
$this->params['breadcrumbs'][] = ['label' => 'Edit' . ' ' . $country['name']];
?>

<div class="country-edit">
    <h1><?= Html::encode($this->title) ?></h1>

  <br>

    <?php $form = ActiveForm::begin([
        'id' => 'country-edit-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-2 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-6 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ]
    ]); ?>


    <?= $form->field($model, 'continent_id')->dropdownList(
        ArrayHelper::map(Continent::find()->asArray()->all(), 'continent_id', 'name'),
        ['options' => [$country['continent_id'] => ['Selected'=>true]]]
    ); ?>

    <?= $form->field($model, 'name')->textInput(['value' => $country['name']]) ?>
    <?= $form->field($model, 'official_name')->textInput(['value' => $country['official_name']]) ?>
    <?= $form->field($model, 'code')->textInput(['value' => $country['code']]) ?>
    <?= $form->field($model, 'area')->textInput(['value' => $country['area']]) ?>
    <?= $form->field($model, 'currency')->textInput(['value' => $country['currency']]) ?>
    <?= $form->field($model, 'capital')->textInput(['value' => $country['capital']]) ?>


    <div class="form-group">
        <div class="offset-lg-7 col-lg-5">
            <?= Html::submitButton('Зберегти', ['class' => 'btn btn-primary', 'name' => 'edit-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

lab03-master/views/country/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;


$this->title = $country->name;
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['continent/index']];
$this->params['breadcrumbs'][] = ['label' => $continent['name'], 'url' => ['continent/view', 'code' => $continent['code']]];
$this->params['breadcrumbs'][] = ['label' => $country['name'], 'url' => ['country/view', 'code' => $country['code']]];


$rep = array('[', ']');
$coords = str_replace($rep, "", $country['coords']);
$coords2 = explode(',', $coords);
$lat = $coords2[0];
$lnd = $coords2[1];
?>


<section id="continent-view">
  <div class="container">
    <div class="country">
      <h1><?= Html::encode($this->title) ?> <a href="<?= Url::to(['country/edit', 'code' => $country->code]); ?>" class="btn btn-sm btn-primary mx-3">Редагувати</a> </h1>
      <div class="wrapper d-flex justify-content-between">
        <div class="country__information col-6">
          <table class="table table-striped table-bordered">
            <tr>
              <th scope="row">Official Name</th>
              <td><?= $country['name'] ?></td>
            </tr>
            <tr>
              <th scope="row">Image</th>
              <td>
                  <?= Html::img('@web/images/countries/png100px/' . strtolower($country['code']) . '.png', ['alt' => $country['name']]) ?>
              </td>
            </tr>
            <tr>
              <th scope="row">Capital</th>
              <td><?= $country['capital'] ?></td>
            </tr>
            <tr>
              <th scope="row">Area</th>
              <td><?= $country['area'] ?></td>
            </tr>
            </tr>
            <tr>
              <th scope="row">Currency</th>
              <td><?= $country['currency'] ?></td>
            </tr>
          </table>

        </div>
        <div class="country__geolocation col-6">
          <script>
              async function initMap() {
                  let centerLatLng = new google.maps.LatLng(<?=$lat?>, <?=$lnd?>);
                  let point = new google.maps.LatLng(<?=$lat?>, <?=$lnd?>);
                  let mapOptions = {
                      center: centerLatLng,
                      zoom: 5
                  }

                  let map = new google.maps.Map(document.querySelector('.country__geolocation'), mapOptions);
                  // Создание метки на карте
                  let marker = new google.maps.Marker({
                      position: point,
                      map: map,
                      title: '<?=$country['name']?>',
                      draggable: false,
                      animation: google.maps.Animation.DROP
                  });
              }
              window.addEventListener('load', initMap)
          </script>
        </div>
      </div>
    </div>
  </div>
</section>